version: '3'
services:
  pretalx:
    image: pretalx/standalone:latest
    container_name: pretalx
    restart: unless-stopped
    depends_on: 
      - redis
      - db
    environment:
      PRETALX_FILESYSTEM_MEDIA: /public/media
      PRETALX_FILESYSTEM_STATIC: /public/static
    ## You can unremark out the ports section if you only need dev testing
    ## Make sure to remove the web section or change the port if you remark this out
    #ports:
    #  - "80:80"
    volumes: 
      - ./conf/pretalx.cfg:/etc/pretalx/pretalx.cfg:ro
      - pretalx-data:/data
      - pretalx-public:/public

  # Hint: This container is for production use needed to serve static and media files
  # See README.md and reverse-proxy-examples for proxying this for TLS/SSL
  web:
    image: nginx:latest
    container_name: pretalx-web
    restart: unless-stopped
    # remove the ports section if you plan to use docker based traefik for tls/ssl endpoint
    ports:
      - "80:80"
    depends_on:
      - pretalx
    # this section is needed if you plan to use traefik as your tls/ssl end point
    labels:
       traefik.docker.network: "pretalxdocker"
       traefik.enable: "true"
    volumes:
      - ./deployment/docker/nginx.conf:/etc/nginx/nginx.conf
      - pretalx-data:/data
      - pretalx-public:/public

  db:
    image: mysql:latest
    container_name: pretalx-db
    restart: unless-stopped
    volumes:
      - pretalx-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: pretalx
      MYSQL_USER: pretalx
      MYSQL_PASSWORD: veryunsecureplschange
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  redis:
    image: redis:latest
    container_name: pretalx-redis
    restart: unless-stopped
    volumes: 
      - pretalx-redis:/data

volumes:
  pretalx-db:
  pretalx-data:
  pretalx-public:
  pretalx-redis:

